# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  
emptyArray: []
# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - support

# Folder Structure
source: ./source
# sass_dir: source/css

page_gen:
  - data: organizations
    template: premium_organization
    name: title
    dir: organizations
    extension: html

  - data: main-categories
    template: base_results
    name: title
    dir: categories
    extension: html

  - data: taxonomy_category
    template: base_results
    name: title
    dir: categories
    extension: html
    
  - data: custom_authors
    template: custom_authors
    name: title
    dir: authors
    extension: html
  
  - data: papers-sample # switch to the papers.json file, before deploy
    template: paper
    name: title
    dir: papers
    extension: html

  - data: authors-sample # switch to the authors.json file, before deploy
    template: base_results
    name: title
    dir: authors
    extension: html

  - data: region-sample # switch to the region.json file, before deploy
    template: base_results
    name: title
    dir: region
    extension: html

  - data: sector-sample # switch to the sector.json file, before deploy
    template: base_results
    name: title
    dir: sector
    extension: html

  - data: tools
    template: base_results
    name: title
    dir: tools
    extension: html

  - data: access
    template: base_results
    name: title
    dir: access
    extension: html

  - data: type
    template: base_results
    name: title
    dir: type
    extension: html

  - data: taxonomy_objective
    template: base_results
    name: title
    dir: objectives
    extension: html

  - data: taxonomy_methodology
    template: base_results
    name: title
    dir: methodologies
    extension: html


